name: Publish Website to Cpanel

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]  # Workflow akan dijalankan pada push ke branch "main"
    
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action  # Nama job
    runs-on: ubuntu-latest  # Menjalankan job di runner Ubuntu terbaru
    
    steps:
      # Langkah 1: Mengambil kode dari repositori
      - name: Checkout Repository
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2  # Mengambil dua commit terakhir (opsional, bisa disesuaikan)
      
      # Langkah 2: Menggunakan FTP-Deploy-Action untuk meng-upload file
      - name: Deploy Website to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}  # Alamat server FTP
          ftp-username: ${{ secrets.FTP_USERNAME }}  # Username FTP
          ftp-password: ${{ secrets.FTP_PASSWORD }}  # Password FTP
